enum Avoid_ConnDirFlag {
  "Avoid::ConnDirNone",
  "Avoid::ConnDirUp",
  "Avoid::ConnDirDown",
  "Avoid::ConnDirLeft",
  "Avoid::ConnDirRight",
  "Avoid::ConnDirAll"
};

typedef unsigned long ConnDirFlags;
typedef sequence<ConnEnd> ConnEndList;

enum Avoid_ConnEndType {
  "Avoid::ConnEndPoint",
  "Avoid::ConnEndShapePin",
  "Avoid::ConnEndJunction",
  "Avoid::ConnEndEmpty",
};

[Prefix="Avoid::"]
interface ConnEnd {
  void ConnEnd([Ref] Point point);
  [Value] ConnEnd createConnEndFromJunctionRef(JunctionRef junctionRef);
  void ConnEnd([Ref] Point point, ConnDirFlags visDirs);
  // NOTE: Cannot use this constructor due to WebIDL overloading limitations
  // Use ShapeConnectionPin instead to create connection points on shapes
  // void ConnEnd(ShapeRef shapeRef, unsigned long connectionPinClassID);
};
